### PR TITLE
blogs.perl.org is using PearlBee

### PR DESCRIPTION
**Pull request by chankeypathak**

### CODE REVIEW

**Comment by itnomad** [comment]
Is blogs.perl.org using PearlBee? The site says it is using Moveable Type.

**Comment by drforr** [comment]
The Beta version (residing at http://blogsperlorg.pearlbee.org/) is, and once the final round of testing is complete will replace the existing blogs.perl.org. (I'm the person who filed the grant application - I've since been moved onto a new project and unfortunately have only minimal involvement with the b.p.org team.)

**Comment by itnomad** [comment]
I found it. I'm getting a login failure. The reset function sends one back to the login page instead of an opportunity to change one's password. What is that weird little switch at the top of the page?

**Comment by drforr** [comment]
The reset-password handler simply sends out an email to the address on file with an embedded link to the page that lets you set your new password; the handler to change passwords is separate. The switch is to toggle between a "light" and "dark" theme for the page, it's stored in your user preferences.

For the actual code see drforr/blogs-perl-org - Active development is being done there at the moment, and the source is freely available. At this point it really can't be easily merged back into PearlBee, I'm not sure what'll be done with this project once it's done.

**Comment by itnomad** [comment]
Thanks. The theme switch is cool. The embedded link does not send me to a page for setting a new password. It sends me to the login page. I apologize. I don't mean to be disruptive. I'm going to attempt to install the main branch today. Also, going to try the suggestion by huache about using an older commit and using his changes to the db file.  Maybe I'll try xsawyers branch again. I tried these in August with no luck. If the code hasn't changed in 7 months, what can I expect?

**Comment by itnomad** [comment]
Thanks, Jeff. This is beginning to make some sense to me now.

**Pull request closed without merging**
